[package]
name = "rust-store-inventory-management-system"
version = "0.1.0"
edition = "2024"

[dependencies]
validator = { version = "0.20.0", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
